
(define (problem block_world)
    (:domain block_world)
    (:objects
        orange purple red blue cyan green yellow pink robot1 - block
    )
    (:init
        (ontable blue)
        (ontable orange)
        (ontable cyan)
        (ontable purple)
        (ontable red)
        (ontable green)
        (ontable yellow)
        (ontable pink)
        (clear orange)
        (clear pink)
        (clear yellow)
        (clear cyan)
        (clear purple)
        (clear red)
        (clear blue)
        (clear green)
        (handempty robot1)
    )
    (:goal
        (and
            (on orange purple)
            (on purple red)
            (on red blue)
            (ontable blue)
            (on green yellow)
            (on yellow pink)
            (ontable pink)
            (ontable cyan)
            (clear orange)
            (clear green)
            (handempty robot1)
        )
    )
)