(define (problem block_world)
    (:domain blocksworld)
    (:objects
        pink green orange red blue yellow purple cyan r1 - block
        robot - robot
    )
    (:init
        (ontable yellow)
        (clear yellow)
        (ontable cyan)
        (clear cyan)
        (ontable orange)
        (clear orange)
        (ontable green)
        (clear green)
        (ontable red)
        (clear red)
        (ontable blue)
        (clear blue)
        (ontable purple)
        (clear pink)
        (on pink purple)
        (on purple blue)
        (on blue r1)
        (ontable r1)
        (handempty robot)
    )
    (:goal
        (and
            (on pink green)
            (on green orange)
            (on orange red)
            (ontable red)
            (on blue yellow)
            (on yellow purple)
            (on purple cyan)
            (ontable cyan)
        )
    )
)