(define (problem contruction_site_pb1)
	(:domain contruction_site)
	(:objects 
	rb1 rb2 - machine 
	mat1 mat2 - loadable_material
   parkingArea1 wp1 wp5 wp7 wp8 parkingArea2 wp2 wp10 wp3 wp4 wp6 wp9 wp11 wp12 - location
	)
	(:init
	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;   
    (forklift rb1)
    (forklift rb2)
    (pallet mat1)
    (pallet mat2)

	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (can_load rb1)
    (can_load rb2)
    
    
    
;; make sure these are constants or objects:
;; parkingArea1 wp1 wp5 wp7 wp8 parkingArea2 wp2 wp10 wp3 wp4 parkingArea3 wp9 wp6 wp11 wp12
    ;;(connected parkingArea1 wp1)
    ;;(connected wp1 parkingArea1)
    ;;(connected wp1 wp5)
    ;;(connected wp5 wp1)
    ;;(connected wp5 wp7)
    ;;(connected wp7 wp5)
    ;;(connected wp7 wp8)
    ;;(connected wp8 wp7)
    ;;(connected parkingArea2 wp2)
    ;;(connected wp2 parkingArea2)
    ;;(connected wp2 wp5)
    ;;(connected wp5 wp2)
    ;;(connected wp5 wp10)
    ;;(connected wp10 wp5)
    ;;(connected wp10 wp3)
    ;;(connected wp3 wp10)
    ;;(connected wp3 wp4)
    ;;(connected wp4 wp3)
    ;;(connected parkingArea3 wp5)
    ;;(connected wp5 parkingArea3)
    ;;(connected wp5 wp9)
    ;;(connected wp9 wp5)
    ;;(connected wp9 wp6)
    ;;(connected wp6 wp9)
    ;;(connected wp5 wp9)
    ;;(connected wp9 wp5)
    ;;(connected wp9 wp11)
    ;;(connected wp11 wp9)
    ;;(connected wp11 wp12)
    ;;(connected wp12 wp11)
    ;;(connected wp5 wp11)
    ;;(connected wp11 wp5)
    
    (idle rb1)
    (idle rb2)
    (at rb1 parkingArea1) 
    (at rb2 parkingArea2)

    (= (total_cost ) 1)
    (armlow rb1 )
    (armlow rb2 ) 
    
    
   (at mat1 wp9)
   (at mat1 wp3)
   (at mat2 wp4)



   
     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
     ;;clear spaces
     (clear wp1) 
     (clear wp2)
     ;;(clear wp3) 
     ;;(clear wp4) 
     (clear wp5)
     (clear wp6) 
     (clear wp7) 
     (clear wp8)
     ;;(clear wp9) 
     (clear wp10) 
     (clear wp11)
     (clear wp12)
     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
     (noMachineAtLocation wp1) 
     (noMachineAtLocation wp2) 
     (noMachineAtLocation wp3) 
     (noMachineAtLocation wp4) 
     (noMachineAtLocation wp5)
     (noMachineAtLocation wp6) 
     (noMachineAtLocation wp7) 
     (noMachineAtLocation wp8)
     (noMachineAtLocation wp9) 
     (noMachineAtLocation wp10) 
     (noMachineAtLocation wp11)
     (noMachineAtLocation wp12) 
     (noMachineAtLocation wp6)
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (clear_path parkingArea1 wp1)
    (clear_path parkingArea1 wp2)
    (clear_path parkingArea1 wp3)
    (clear_path parkingArea1 wp4)
    (clear_path parkingArea1 wp5)
    (clear_path parkingArea1 wp6)
    (clear_path parkingArea1 wp7)
    (clear_path parkingArea1 wp8)
    (clear_path parkingArea1 wp9)
    (clear_path parkingArea1 wp10)
    (clear_path parkingArea1 wp11)
    (clear_path parkingArea1 wp12)
    
    (clear_path parkingArea2 wp1)
    (clear_path parkingArea2 wp2)
    (clear_path parkingArea2 wp3)
    (clear_path parkingArea2 wp4)
    (clear_path parkingArea2 wp5)
    (clear_path parkingArea2 wp6)
    (clear_path parkingArea2 wp7)
    (clear_path parkingArea2 wp8)
    (clear_path parkingArea2 wp9)
    (clear_path parkingArea2 wp10)
    (clear_path parkingArea2 wp11)
    (clear_path parkingArea2 wp12)
    
    
    

    (clear_path wp1 wp2)
    (clear_path wp1 wp3)
    (clear_path wp1 wp4)
    (clear_path wp1 wp5)
    (clear_path wp1 wp6)
    (clear_path wp1 wp7)
    (clear_path wp1 wp8)
    (clear_path wp1 wp9)
    (clear_path wp1 wp10)
    (clear_path wp1 wp11)
    (clear_path wp1 wp12)
    
    (clear_path wp2 wp1)
    (clear_path wp2 wp3)
    (clear_path wp2 wp4)
    (clear_path wp2 wp5)
    (clear_path wp2 wp6)
    (clear_path wp2 wp7)
    (clear_path wp2 wp8)
    (clear_path wp2 wp9)
    (clear_path wp2 wp10)
    (clear_path wp2 wp11)
    (clear_path wp2 wp12)
    
    (clear_path wp3 wp1)
    (clear_path wp3 wp2)
    (clear_path wp3 wp4)
    (clear_path wp3 wp5)
    (clear_path wp3 wp6)
    (clear_path wp3 wp7)
    (clear_path wp3 wp8)
    (clear_path wp3 wp9)
    (clear_path wp3 wp10)
    (clear_path wp3 wp11)
    (clear_path wp3 wp12)
    
    (clear_path wp4 wp1)
    (clear_path wp4 wp2)
    (clear_path wp4 wp3)
    (clear_path wp4 wp5)
    (clear_path wp4 wp6)
    (clear_path wp4 wp7)
    (clear_path wp4 wp8)
    (clear_path wp4 wp9)
    (clear_path wp4 wp10)
    (clear_path wp4 wp11)
    (clear_path wp4 wp12)
    
    (clear_path wp5 wp1)
    (clear_path wp5 wp2)
    (clear_path wp5 wp3)
    (clear_path wp5 wp4)
    (clear_path wp5 wp6)
    (clear_path wp5 wp7)
    (clear_path wp5 wp8)
    (clear_path wp5 wp9)
    (clear_path wp5 wp10)
    (clear_path wp5 wp11)
    (clear_path wp5 wp12)
    
    (clear_path wp6 wp1)
    (clear_path wp6 wp2)
    (clear_path wp6 wp3)
    (clear_path wp6 wp4)
    (clear_path wp6 wp5)
    (clear_path wp6 wp7)
    (clear_path wp6 wp8)
    (clear_path wp6 wp9)
    (clear_path wp6 wp10)
    (clear_path wp6 wp11)
    (clear_path wp6 wp12)
    
    (clear_path wp7 wp1)
    (clear_path wp7 wp2)
    (clear_path wp7 wp3)
    (clear_path wp7 wp4)
    (clear_path wp7 wp5)
    (clear_path wp7 wp6)
    (clear_path wp7 wp8)
    (clear_path wp7 wp9)
    (clear_path wp7 wp10)
    (clear_path wp7 wp11)
    (clear_path wp7 wp12)
    
    (clear_path wp8 wp1)
    (clear_path wp8 wp2)
    (clear_path wp8 wp3)
    (clear_path wp8 wp4)
    (clear_path wp8 wp5)
    (clear_path wp8 wp6)
    (clear_path wp8 wp7)
    (clear_path wp8 wp9)
    (clear_path wp8 wp10)
    (clear_path wp8 wp11)
    (clear_path wp8 wp12)
    
    (clear_path wp9 wp1)
    (clear_path wp9 wp2)
    (clear_path wp9 wp3)
    (clear_path wp9 wp4)
    (clear_path wp9 wp5)
    (clear_path wp9 wp6)
    (clear_path wp9 wp7)
    (clear_path wp9 wp8)
    (clear_path wp9 wp10)
    (clear_path wp9 wp11)
    (clear_path wp9 wp12)
    
    (clear_path wp10 wp1)
    (clear_path wp10 wp2)
    (clear_path wp10 wp3)
    (clear_path wp10 wp4)
    (clear_path wp10 wp5)
    (clear_path wp10 wp6)
    (clear_path wp10 wp7)
    (clear_path wp10 wp8)
    (clear_path wp10 wp9)
    (clear_path wp10 wp11)
    (clear_path wp10 wp12)
    
    (clear_path wp11 wp1)
    (clear_path wp11 wp2)
    (clear_path wp11 wp3)
    (clear_path wp11 wp4)
    (clear_path wp11 wp5)
    (clear_path wp11 wp6)
    (clear_path wp11 wp7)
    (clear_path wp11 wp8)
    (clear_path wp11 wp9)
    (clear_path wp11 wp10)
    (clear_path wp11 wp12)
    
    (clear_path wp12 wp1)
    (clear_path wp12 wp2)
    (clear_path wp12 wp3)
    (clear_path wp12 wp4)
    (clear_path wp12 wp5)
    (clear_path wp12 wp6)
    (clear_path wp12 wp7)
    (clear_path wp12 wp8)
    (clear_path wp12 wp9)
    (clear_path wp12 wp10)
    (clear_path wp12 wp11)
    
     )
	(:goal (and 
	(on mat1 mat2 wp10)
	))
	(:metric minimize(total_cost))
)
