
(define (problem block_world)
    (:domain blocksworld)
    (:objects
        pink cyan orange red yellow green blue purple robot - block robot
    )
    (:init
        (ontable pink)
        (ontable cyan)
        (ontable orange)
        (ontable red)
        (ontable yellow)
        (ontable green)
        (ontable blue)
        (ontable purple)
        (clear yellow)
        (clear orange)
        (clear green)
        (clear purple)
        (clear robot)
        (on yellow pink)
        (on orange cyan)
        (on green red)
        (on purple blue)
        (handempty robot)
    )
    (:goal
        (and
            (on blue green)
            (on green purple)
            (on purple yellow)
            (on yellow red)
            (on red orange)
            (on orange cyan)
            (on cyan pink)
            (ontable pink)
            (clear blue)
        )
    )
)