(define (problem block_world)
    (:domain blocksworld)
    (:objects
        red green yellow purple blue pink orange cyan robot - block robot
    )
    (:init
        (ontable cyan)
        (ontable orange)
        (ontable pink)
        (ontable blue)
        (ontable green)
        (ontable red)
        (ontable yellow)
        (ontable purple)
        (clear cyan)
        (clear orange)
        (clear blue)
        (clear green)
        (clear red)
        (clear yellow)
        (clear purple)
        (clear pink)
        (handempty robot)
    )
    (:goal
        (and
            (on green yellow)
            (on yellow purple)
            (on purple red)
            (ontable red)
            (clear green)
            (on blue pink)
            (on pink orange)
            (on orange cyan)
            (ontable cyan)
            (clear blue)
        )
    )
)